Swissalp s ehlphabet stickers
pandorabox-io/pandorabox_custom pull request #53
Opened 2022-01-25 01:26 UTC by SwissalpS

adds missing recipes for mandarin stickers

I'm not sure we really need this though.
Arguably we could also move the recipe override into this file too (from crafts.lua)

2022-01-25 04:04 UTC, OgelGames requested changes

2022-01-25 04:04 UTC, OgelGames commented on init.lua
> +dofile(MP.."/ehlphabet.lua")
```suggestion
-- ehlphabet stickers
if minetest.get_modpath('ehlphabet') then
	dofile(MP.."/ehlphabet.lua")
end
```

2022-01-25 04:04 UTC, OgelGames commented on ehlphabet.lua
> +if not minetest.get_modpath('ehlphabet') then return end
```suggestion
```

2022-01-25 04:21 UTC, OgelGames commented
Hmm... This doesn't work for me... 🤔

2022-01-25 05:28 UTC, SwissalpS commented
> Hmm... This doesn't work for me... thinking

As in you don't like the concept or as in it doesn't technically work and doesn't add the recipes for you?

2022-01-25 05:45 UTC, OgelGames commented
It doesn't add the recipes.

2022-01-25 06:49 UTC, BuckarooBanzay commented
this is essentially the same as this one: https://github.com/minetest-mirrors/ehlphabet/pull/1 right?
We could merge this and remove it ~~never~~afterwards when the upstream repo has accepted the changes

2022-01-26 00:50 UTC, SwissalpS commented
> this is essentially the same as this one: [minetest-mirrors/ehlphabet#1](https://github.com/minetest-mirrors/ehlphabet/pull/1) right? We could merge this and remove it ~never~afterwards when the upstream repo has accepted the changes

yes, that's what it's about. It's nothing urgent, we could also wait a couple months until upstream ads them too ;)

2022-01-26 00:53 UTC, SwissalpS commented
> It doesn't add the recipes.

weird, admittedly I didn't test in this exact configuration. Will give it another try soon. (not high on my priorities list)

2022-01-26 11:52 UTC, SwissalpS commented
OK, I see what you mean now. I've been testing with inspection tool which does show the recipes now but unified_inventory does not pick them up for some reason.
Possibly registering a crafting method for the ingredients is required.

2022-01-26 12:50 UTC, OgelGames commented
Ah, it's probably because they have the `not_in_creative_inventory` group 🤦

> Possibly registering a crafting method for the ingredients is required.

How are the "stickers" created currently? I didn't see a way to make them with the letter machine... 🤔

2022-01-26 15:00 UTC, SwissalpS commented
insert paper for stickers, ehlphabet blocks for blocks.

2022-01-26 15:01 UTC, SwissalpS commented
> Ah, it's probably because they have the `not_in_creative_inventory` group

thanks. Makes sense for the normal characters.

2022-01-26 15:28 UTC, SwissalpS commented
fixed it in my PR to mirror repo https://github.com/minetest-mirrors/ehlphabet/pull/1/commits/46abfc243d2a4d8951d2400b4640503caf94da3c

doing an override here seems overkill :/

2022-01-26 16:49 UTC, SwissalpS commented
FYI: on this branch https://github.com/SwissalpS/ehlphabet/tree/unified_inventorCompat I've added unified_inventory support which adds all the items to crafting guide with 'printing' method.

2024-12-06 10:47 UTC, SwissalpS commented
Do we:
1) drop these fixes, since Och_Noe doesn't seem to react (or I'm incabable)
2) move my fork to this org or mt-mods and manage it ourselves

2024-12-12 13:07 UTC, BuckarooBanzay commented
> move my fork to this org or mt-mods and manage it ourselves

i'm in favor of this :point_up: `Och_Noe` et al seem to be in their own bubble and they are making it _very_ hard to contribute anything :/

2024-12-12 13:26 UTC, SwissalpS commented
mt-mods
or
pandorabox-io?

2024-12-13 18:34 UTC, BuckarooBanzay commented
> mt-mods or pandorabox-io?

might be of use outside of pandorabox so i would go with `mt-mods` :wink:

2024-12-13 19:44 UTC, SwissalpS commented
Sounds good. Once ready, let me know and I'll PR my branch.

2024-12-14 17:31 UTC, BuckarooBanzay commented
> Sounds good. Once ready, let me know and I'll PR my branch.

moved the whole thing to https://github.com/mt-mods/ehlphabet, you should have full access :+1:

2024-12-14 17:31 UTC, closed without merging

2024-12-15 21:30 UTC, SwissalpS commented
Now that my changes are merged to mt-mods repo, I realize that this increases the node-count quite a bit. Labels can do pretty much what stickers can.
I do like though, that stickers require a machine to make and aren't just some fancy signs.